// <auto-generated />
using IquitosDelivery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IquitosDelivery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608195500_AddGoogleCustomerLogin")]
    partial class AddGoogleCustomerLogin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
